guydavis/machinaris

- CHANGELOG.md
- CREDITS.md
- app/commands/chia_cli.py
- app/commands/plotman_cli.py
- app/models/chia.py
- app/routes.py
- app/templates/base.html
- app/templates/network/connections.html
- start.sh
Updated changelog and few minor fixes.
> Last updates for v0.2 release.

- CHANGELOG.md
- CREDITS.md
- README.md
- app/commands/chia_cli.py
- app/commands/global_config.py
- app/routes.py
- app/static/styles.css
- app/templates/base.html
- app/templates/network/blockchain.html
- app/templates/network/connections.html
- app/templates/settings/farming.html
- app/templates/settings/plotting.html
- dockerfile
- patch_chia.sh
- Dark mode CSS patch contributed by Hukuma1.  Looks great! Thanks for the help!
- Patch to latest Chia binaries version at 1.1.6.  Thanks to ChrisM! Nice solution!
- Fix broken 'Add Connection' button on Network | Connections page.
> Patch to latest Chia 1.1.6

- app/commands/chia_log_parser.py
- app/commands/chiadog_cli.py
- app/models/chia_logs.py
- app/models/plotman.py
- app/routes.py
- app/templates/index.html
> Display recent block challenges

- app/commands/log_parser.py
- app/models/log.py
- app/routes.py
- app/templates/alerts.html
- app/templates/farming.html
- app/templates/logs.html
- app/templates/plotting.html
- config/plotman.sample.yaml
For the 3 main log files: Chiadog, Chia, and Plotman.  Still to do is log-viewer for each running plot job.
> Adding log viewer for plotting, farming, and alerts.

- app/commands/log_parser.py
- app/commands/plotman_cli.py
- app/models/log.py
- app/models/plotman.py
- app/routes.py
- app/templates/alerts.html
- app/templates/farming.html
- app/templates/logs.html
- app/templates/plotting.html
- config/plotman.sample.yaml
> Log Viewer and Dockerfile cleanup contributed by sparklyballs

- CHANGELOG.md
- CREDITS.md
- README.md
- app/commands/chia_cli.py
- app/commands/log_parser.py
- app/commands/plotman_cli.py
- app/routes.py
- app/templates/alerts.html
- app/templates/base.html
- app/templates/farming.html
- app/templates/plots_check.html
- app/templates/plotting.html
1. If plot created locally via Plotman, can display the Analyze timing output.
2. Log viewer for output (many minutes) of a `chia plots check` command.
> Farming page - new view actions

- app/__init__.py
- app/commands/chia_cli.py
- app/commands/chiadog_cli.py
- app/commands/global_config.py
- app/commands/log_parser.py
- app/schedules/__init__.py
- app/schedules/disk_stats.py
- app/schedules/farm_stats.py
- app/templates/farming.html
- app/templates/keys.html
- app/templates/network/blockchain.html
- app/templates/network/connections.html
- app/templates/wallet.html
- app/utils.py
- requirements.txt
- scripts/setup_databases.sh
Also guards for plotting only mode.
> Disk stats collection.

- .github/workflows/chiapos.yaml
- dockerfile
- scripts/setup_databases.sh
For those who want to try it on their systems.  Most will still want the mainline release using stock Chia binaries.
> Ability to build a separate Docker image with Chiapos patch

- dockerfile
- scripts/patch_chiapos.sh
> Passing variable to script.

- .github/workflows/develop.yaml
- .github/workflows/main.yaml
- .github/workflows/test.yaml
- CHANGELOG.md
- app/commands/global_config.py
- dockerfile
https://github.com/Chia-Network/chia-blockchain/blob/1.1.7/CHANGELOG.md#117-chia-blockchain-2021-06-05
> v0.3.2 - update to include Chia v1.1.7

- api/commands/chiadog_cli.py
- api/models/chia.py
- web/actions/chiadog.py
- web/actions/plotman.py
- web/actions/worker.py
- web/routes.py
- web/templates/alerts.html
- web/templates/settings/alerts.html
- web/templates/settings/farming.html
- web/templates/settings/plotting.html
Also, download button for Settings.
> Fixes for Alerts pages.

- README.md
- licenses/LICENSE_madmax_plotter.txt
- scripts/plotman_migrate.py
> Upgrade fix for Plotman config.

- dockerfile
- web/models/chia.py
Also make Flax enabled by default as enabling it is causing problems for some.
> Guard against round on None.

- .github/workflows/develop.yaml
- .github/workflows/main.yaml
- .github/workflows/test.yaml
- api/commands/chia_cli.py
- api/commands/chiadog_cli.py
- api/commands/log_parser.py
- api/machinaris.postman_collection.json
- api/views/configs/resources.py
- config/chiadog.sample.yaml
- config/flaxdog.sample.yaml
- scripts/chia_install.sh
- scripts/chiadog_launch.sh
- scripts/flax_launch.sh
- scripts/flaxdog_launch.sh
- scripts/plotman_install.sh
- web/actions/chia.py
- web/actions/chiadog.py
- web/routes.py
- web/templates/alerts.html
- web/templates/settings/alerts.html
- web/templates/settings/farming.html
- web/templates/settings/plotting.html
As per [these instructions](https://xchpool.org/guide-to-chia-farming/).  Start of #131
> Testing of Chia pooling protocol

- .github/workflows/develop.yaml
- .github/workflows/main.yaml
- .github/workflows/test.yaml
- CHANGELOG.md
- scripts/chia_install.sh
- web/models/chia.py
Also fix ETW calc for old Flax code-base.
> Pull in latest Plotman upstream fixes.

- .github/workflows/develop.yaml
- api/models/chia.py
- config/plotman.sample.yaml
- web/actions/chia.py
- web/models/chia.py
- web/templates/settings/pools.html
> plotnft join

- scripts/start_machinaris.sh
- web/templates/worker_launch.html
> Worker launch fixes.

- api/commands/plotman_cli.py
- dockerfile
- web/models/chia.py
- web/templates/logs.html
- web/templates/worker_launch.html
- web/templates/workers.html
- Docker compose fixes
- Clean `tmp2` on plotman launch
- Plot kill now takes --force switch
> Misc fixes.

- CHANGELOG.md
- api/commands/chiadog_cli.py
- config/plotman.sample.yaml
- scripts/chiadog_launch.sh
- scripts/plotman_install.sh
- web/actions/plotman.py
- web/routes.py
- web/templates/alerts.html
- web/templates/settings/plotting.html
- web/templates/worker_launch.html
> More fixes and improvements.

- api/gunicorn.conf.py
- api/rpc/chia.py
- api/views/plots/resources.py
- scripts/chia_launch.sh
- scripts/flax_launch.sh
> Fixes and optimizations.

- CHANGELOG.md
- scripts/dev/start-api.sh
- scripts/dev/start-web.sh
- scripts/flaxdog_install.sh
- scripts/start_machinaris.sh
> Latest fixes and doc updates.

- web/templates/worker_launch.html
- web/templates/workers.html
> Support paths in Worker volume paths.

- README.md
> Add TrueNAS to main page

- api/commands/chiadog_cli.py
- common/models/farms.py
- web/actions/chia.py
- web/actions/plotman.py
- web/actions/stats.py
- web/actions/worker.py
- web/routes.py
- web/rpc/chia.py
- web/templates/farming/plots.html
- web/templates/plots_check.html
- web/templates/worker.html
- web/templates/workers.html
> Worker page, with warnings.

- api/commands/log_parser.py
- api/schedules/status_partials.py
- api/views/partials/resources.py
- web/actions/chia.py
- web/actions/worker.py
- web/models/chia.py
> Fixes for partials and warnings.

- CREDITS.md
- README.md
- api/commands/chiadog_cli.py
- api/commands/log_parser.py
- api/log.conf
- api/schedules/stats_disk.py
- api/schedules/status_partials.py
- api/views/logs/resources.py
- common/utils/converters.py
- scripts/dev/start-api.sh
- scripts/dev/start-web.sh
- scripts/start_machinaris.sh
- web/actions/worker.py
- web/log.conf
- web/routes.py
- web/templates/worker_launch.html
- web/templates/workers.html
> Logging and performance fixes.

- api/log.conf
- web/log.conf
> Fails to start without access file key even if unused.

- api/commands/chia_cli.py
- api/gunicorn.conf.py
- api/models/chia.py
- api/rpc/chia.py
- api/schedules/status_alerts.py
- api/schedules/status_blockchains.py
- api/schedules/status_challenges.py
- api/schedules/status_connections.py
- api/schedules/status_controller.py
- api/schedules/status_farm.py
- api/schedules/status_keys.py
- api/schedules/status_partials.py
- api/schedules/status_plotnfts.py
- api/schedules/status_plots.py
- api/schedules/status_plotting.py
- api/schedules/status_points.py
- api/schedules/status_pools.py
- api/schedules/status_wallets.py
- api/views/plots/resources.py
- scripts/setup_databases.sh
- web/models/chia.py
> Improve plot tracking.

- scripts/setup_databases.sh
> Exclude fullnode.

- .github/workflows/develop.yaml
- .github/workflows/main.yaml
- .github/workflows/test.yaml
- CHANGELOG.md
> Chia 1.2.6

- web/actions/chia.py
- web/actions/plotman.py
- web/actions/stats.py
- web/actions/worker.py
- web/models/chia.py
- web/models/chiadog.py
- web/models/worker.py
- web/templates/farming/workers.html
- web/templates/keys.html
- web/templates/network/blockchain.html
- web/templates/network/connections.html
- web/templates/wallet.html
- web/templates/worker.html
> Support IP address for controller as well.

- CHANGELOG.md
- common/config/globals.py
- common/utils/converters.py
- config/plotman.sample.yaml
- dockerfile
- entrypoint.sh
- scripts/bladebit_clone.sh
- scripts/bladebit_make.sh
- scripts/start_machinaris.sh
- web/actions/worker.py
- web/models/chia.py
- web/models/worker.py
- web/templates/base.html
- web/templates/farming/workers.html
- web/templates/plotting/workers.html
- web/templates/pools.html
- web/templates/settings/pools.html
> Plotman support for Bladebit

- api/commands/log_parser.py
- api/schedules/status_challenges.py
- scripts/bladebit_make.sh
> Don't build Bladebit on harvesters.

- docker/dockerfile
- scripts/bladebit_make.sh
Looks like Bladebit 1.2.0 was just release with a different build process.  This should work but am unable to test myself.
> Bladebit 1.2.0 Changes

- docker/dockerfile
*Compiles binaries in a separate container
*Saves around 300mb on the docker image
> Dockerfile improvements

- docker/dockerfile
- scripts/forks/flax_launch.sh
> Update ports for forks.

- docker/dockerfile
Hopefully this fixes bladebit as noted in Discord
> missed bladebit dependancy

- docker/dockerfile
Bladebit worked with these installed.  Switching back and will research further.
> Reverting changes

- CHANGELOG.md
- scripts/bladebit_build.sh
- web/templates/worker_launch.html
> Fix New Worker page and optionally skip bladebit building.

- .github/workflows/develop-chia.yaml
- .github/workflows/main-chia.yaml
- .github/workflows/test-chia.yaml
- CHANGELOG.md
- CREDITS.md
- README.md
- web/actions/chia.py
> Chia 1.2.11

- scripts/forks/chia_launch.sh
- scripts/forks/chives_launch.sh
- scripts/forks/flax_launch.sh
- scripts/forks/flora_launch.sh
- scripts/forks/hddcoin_launch.sh
- scripts/forks/nchain_launch.sh
- scripts/forks/silicoin_launch.sh
- scripts/forks/staicoin_launch.sh
- web/actions/chia.py
> Support persistent key handling.

- CHANGELOG.md
- scripts/forks/chia_launch.sh
- scripts/forks/chives_launch.sh
- scripts/forks/flax_launch.sh
- scripts/forks/flora_launch.sh
- scripts/forks/hddcoin_launch.sh
- scripts/forks/nchain_launch.sh
- scripts/forks/silicoin_launch.sh
- scripts/forks/staicoin_launch.sh
- web/actions/chia.py
> Disable blockchain db download by default.

- CHANGELOG.md
- api/gunicorn.conf.py
- api/schedules/nft_recover.py
- config/plotman.sample-chives.yaml
- config/plotman.sample.yaml
- scripts/forks/cactus_launch.sh
- scripts/forks/chia_launch.sh
- scripts/forks/chives_launch.sh
- scripts/forks/flax_launch.sh
- scripts/forks/flora_launch.sh
- scripts/forks/hddcoin_launch.sh
- scripts/forks/nchain_launch.sh
- scripts/forks/silicoin_launch.sh
- scripts/forks/staicoin_launch.sh
- scripts/forks/stor_launch.sh
> Fixes from testing & doc updates.

- api/models/plotman.py
- scripts/dev/start-api.sh
> Another attempt at parsing bladebit plotman lines.

- docker/entrypoint.sh
- scripts/plotman_autoplot.sh
- scripts/plotman_setup.sh
> Setup plotman early, but don't auto_plot until everything else ready.

- api/models/plotman.py
- scripts/dev/start-api.sh
> Guard on plotman status parsing.

- api/schedules/plots_check.py
- common/utils/converters.py
- web/actions/plotman.py
- web/actions/worker.py
- web/models/chia.py
- web/models/worker.py
> Disabling debug logging.

- api/commands/plotman_cli.py
- api/schedules/status_plotting.py
> More guards for slow build times.

- CHANGELOG.md
- web/models/worker.py
> Adding guard against missing worker.config.

- web/templates/plotting/jobs.html
- web/templates/plotting/workers.html
> Label fixes

- scripts/start_machinaris.sh
> Fix plotman replace on launch of plotter.

- CHANGELOG.md
- web/actions/stats.py
- web/actions/worker.py
> More bug fixes.

- CHANGELOG.md
- scripts/farmr_setup.sh
- web/actions/stats.py
- web/routes.py
- web/static/landings.txt
- web/templates/base.html
- web/templates/plotting/jobs.html
- web/templates/worker_launch.html
> Plotting speed graphs

- api/schedules/plots_check.py
- api/schedules/stats_farm.py
> Optimize check lookup efficiency.

- config/chiadog/btcgreen.sample.yaml
> Chiadog config for BTCGreen.

- scripts/farmr_setup.sh
> Another fix for farmr skip launch.

- CHANGELOG.md
- api/schedules/log_rotate.py
- config/chiadog/staicoin.sample.yaml
- scripts/forks/mmx_launch.sh
- scripts/forks/staicoin_launch.sh
> More Staicoin fixes for their blockchain renaming.

- scripts/farmr_setup.sh
Hi!
Please review my addons/corrections so we can have some more flexibility regarding installing/using `farmr`
> Farmr script update

- .gitignore
- docker/dockerfile
- scripts/pull_3rd_party_libs.sh
- web/templates/base.html
- web/templates/controller.html
- web/templates/logs.html
- web/templates/setup.html
- web/templates/worker_launch.html
I know you disliked my idea, but this fixes #537. I just really dislike CDNs, esp. when selfhosting services.
I tested it as good as i can & everything seems to work just fine.
> Change: Local 3rd party libs

- api/commands/mmx_cli.py
- api/commands/pools_cli.py
- api/views/configs/resources.py
- common/config/globals.py
- scripts/forks/btcgreen_install.sh
- scripts/forks/cactus_install.sh
- scripts/forks/chia_install.sh
- scripts/forks/chives_install.sh
- scripts/forks/cryptodoge_install.sh
- scripts/forks/flax_install.sh
- scripts/forks/flora_install.sh
- scripts/forks/hddcoin_install.sh
- scripts/forks/maize_install.sh
- scripts/forks/mmx_install.sh
- scripts/forks/mmx_launch.sh
- scripts/forks/nchain_install.sh
- scripts/forks/shibgreen_install.sh
- scripts/forks/staicoin_install.sh
- scripts/forks/stor_install.sh
- web/actions/stats.py
- web/routes.py
- web/templates/settings/alerts.html
- web/templates/settings/pools.html
- web/templates/settings/tools.html
> Recent fixes from Discord.

- scripts/forks/mmx_install.sh
- scripts/forks/mmx_launch.sh
AMD APU Ryzen 2400GE has been tested.
> Add AMD GPU support.

- .github/workflows/main-mmx.yaml
> Fix MMX branch.

- .github/workflows/main-mmx.yaml
> Another fix for MMX release workflow.

- .github/workflows/develop-chia.yaml
- .github/workflows/develop-mmx.yaml
- .github/workflows/main-chia.yaml
- .github/workflows/main-mmx.yaml
- .github/workflows/test-chia.yaml
- .github/workflows/test-mmx.yaml
- CHANGELOG.md
- api/commands/pools_cli.py
- config/chiadog/silicoin.sample.yaml
- docker/entrypoint.sh
- scripts/chiadog_setup.sh
- scripts/forks/chia_install.sh
- scripts/plotman_setup.sh
- web/actions/chia.py
- web/models/chia.py
- web/routes.py
- web/templates/alerts.html
- web/templates/connections.html
- web/templates/settings/pools.html
> Chia 1.3 beta

- api/translations/pt/LC_MESSAGES/messages.po
- web/translations/pt/LC_MESSAGES/messages.po
Initial version of the Portuguese European translation.
> Portuguese pt_PT translation

- web/static/landings/pt_PT.txt
- web/translations/pt_PT/LC_MESSAGES/messages.po
> Minor PT translation improvements.

- web/templates/farming/workers.html
> Fix for broken error message due to i18n.

- api/commands/websvcs.py
- api/gunicorn.conf.py
- api/schedules/status_wallets.py
- web/models/chia.py
> Fix price lookup and debug wallet parsing.

- api/commands/websvcs.py
- api/gunicorn.conf.py
- api/schedules/status_wallets.py
- web/models/chia.py
- web/templates/farming/workers.html
> Exchange prices fix and wallet parsing debug.

- api/translations/nl_NL/LC_MESSAGES/messages.po
- web/static/landings/nl_NL.txt
- web/translations/nl_NL/LC_MESSAGES/messages.po
Created first nl_NL translation.
> Created nl_NL translation

- CHANGELOG.md
- api/models/drives.py
- api/schedules/status_drives.py
- web/actions/drives.py
- web/models/drives.py
- web/templates/drives.html
> Fixes for drives with no smartctl info.

- web/translations/pt_PT/LC_MESSAGES/messages.po
> Update pt_PT translation from Drive section.

- CHANGELOG.md
- api/models/drives.py
- web/translations/pt_PT/LC_MESSAGES/messages.po
> Translations

- web/translations/pt_PT/LC_MESSAGES/messages.po
> Update pt_PT translations

- web/translations/pt_PT/LC_MESSAGES/messages.po
> Update pt_PT translation.

- web/translations/pt_PT/LC_MESSAGES/messages.po
> Update pt_PT translation

- CHANGELOG.md
- api/commands/chia_cli.py
- api/default_settings.py
- scripts/forks/flax_install.sh
- scripts/forks/mmx_install.sh
- scripts/pull_3rd_party_libs.sh
- web/actions/plotman.py
- web/actions/stats.py
- web/models/chia.py
> Fixes for Datatables.js i18n error in version 1.12.0.  Now using 1.12.1.

- api/commands/websvcs.py
- scripts/bladebit_setup.sh
- scripts/forks/btcgreen_launch.sh
- scripts/forks/shibgreen_launch.sh
- scripts/forktools_setup.sh
- scripts/madmax_setup.sh
> Fixes for v0.8.0

- scripts/forks/mmx_install.sh
- web/templates/worker.html
> Guard for error if no drive stats yet.

- .github/workflows/test-bpx.yaml
- .github/workflows/test-btcgreen.yaml
- .github/workflows/test-cactus.yaml
- .github/workflows/test-chia.yaml
- .github/workflows/test-chives.yaml
- .github/workflows/test-cryptodoge.yaml
- .github/workflows/test-ecostake.yaml
- .github/workflows/test-flax.yaml
- .github/workflows/test-flora.yaml
- .github/workflows/test-hddcoin.yaml
- .github/workflows/test-maize.yaml
- .github/workflows/test-nchain.yaml
- .github/workflows/test-petroleum.yaml
- .github/workflows/test-profit.yaml
- .github/workflows/test-shibgreen.yaml
- .github/workflows/test-silicoin.yaml
- .github/workflows/test-staicoin.yaml
- .github/workflows/test-stor.yaml
- scripts/forks/cryptodoge_install.sh
- scripts/forks/mmx_install.sh
- scripts/madmax_setup.sh
> Use dev branch of Chiadog for test images.

- config/chiadog/bpx.sample.yaml
- config/chiadog/ecostake.sample.yaml
- config/chiadog/petroleum.sample.yaml
- config/chiadog/profit.sample.yaml
> Fix Chiadog configs.

- CHANGELOG.md
- api/commands/rpc.py
- api/commands/websvcs.py
- api/translations/de_DE/LC_MESSAGES/messages.po
- api/translations/fr_FR/LC_MESSAGES/messages.po
- api/translations/it_IT/LC_MESSAGES/messages.po
- api/translations/nl_NL/LC_MESSAGES/messages.po
- api/translations/pt_PT/LC_MESSAGES/messages.po
- api/translations/zh/LC_MESSAGES/messages.po
- scripts/forks/chia_install.sh
- web/actions/drives.py
- web/routes.py
- web/templates/drives.html
- web/templates/workers.html
- web/translations/de_DE/LC_MESSAGES/messages.po
- web/translations/fr_FR/LC_MESSAGES/messages.po
- web/translations/it_IT/LC_MESSAGES/messages.po
- web/translations/nl_NL/LC_MESSAGES/messages.po
- web/translations/pt_PT/LC_MESSAGES/messages.po
- web/translations/zh/LC_MESSAGES/messages.po
> Delete of stale drives status.

- .github/workflows/develop-chia.yaml
- api/commands/websvcs.py
> Switch to working Chia:latest.

- api/commands/rpc.py
> Fix for Silicoin

- api/commands/websvcs.py
> Another fix for stale cache format.

- api/commands/rpc.py
- api/commands/websvcs.py
> Integration

- scripts/forks/ecostake_launch.sh
- scripts/forks/profit_launch.sh
> Latest blockchain DBs

- common/config/blockchains.json
> Fix for Maize RPC port.

- CHANGELOG.md
> Note about Cactus SSL.

- CHANGELOG.md
- api/models/chia.py
- docker/requirements.txt
- scripts/forks/cactus_launch.sh
- web/models/chia.py
> Ignore DECENTRALIZED_ID in wallet balances.

- scripts/forks/cactus_launch.sh
> Fix typo in Cactus launch.

- .github/workflows/develop-chia.yaml
- CHANGELOG.md
> Chia v1.5.0

- scripts/forks/mmx_install.sh
> Latest MMX build.

- api/commands/smartctl.py
> Use standby mode for smartctl polling.

- web/translations/de_DE/LC_MESSAGES/messages.po
updated some Translations, added newer ones.
> updated Translation

- api/gunicorn.conf.py
> Trigger another build against latest base.

- api/commands/chia_cli.py
> Fixes for Cactus CLI renamings.

- .github/workflows/develop-chia.yaml
- .github/workflows/main-chia.yaml
- .github/workflows/test-chia.yaml
- CHANGELOG.md
- scripts/forks/mmx_install.sh
> More testing of Chia 1.6.1

- .github/workflows/develop-chives.yaml
- .github/workflows/main-chives.yaml
- .github/workflows/test-chives.yaml
- api/gunicorn.conf.py
- api/models/mmx.py
- common/config/globals.py
- scripts/forks/mmx_install.sh
- web/routes.py
- web/templates/settings/plotting.html
> Latest fixes for v0.8.5 from testing MMX.

- CHANGELOG.md
- CREDITS.md
- api/commands/plotman_cli.py
- scripts/forks/mmx_install.sh
- scripts/forks/tad_install.sh
> Chia 1.6.1

- CHANGELOG.md
- common/config/globals.py
- scripts/forks/tad_install.sh
> Rollback to working Tad @ v.1.5.0.

- CHANGELOG.md
> Updated Changelog.

- scripts/forks/flora_launch.sh
> Fix quote for Flora.

- CHANGELOG.md
- scripts/forks/flora_launch.sh
> Flora launch fix.

- web/actions/stats.py
> Latest disk stats fix.

- scripts/forks/gigahorse_launch.sh
> Fix for Gigahorse farmer port replacement.

- .github/workflows/main-cactus.yaml
> Duplicate provenance line correction.

- CHANGELOG.md
- config/plotman.sample-chives.yaml
- config/plotman.sample-gigahorse.yaml
- config/plotman.sample-mmx.yaml
- config/plotman.sample.yaml
> Fix plotting templates for Gigahorse.

- web/actions/pools.py
- web/models/pools.py
- web/routes.py
> Exclude Gigahorse from pools config. Do it in Chia.

- .github/workflows/main-chia.yaml
- .github/workflows/test-chia.yaml
> Use cuda branch for Bladebit in release.

- .github/workflows/main-chives.yaml
- .github/workflows/test-chives.yaml
- CHANGELOG.md
> More  provenance fixes for Chives images.

- .github/workflows/main-chia.yaml
- .github/workflows/test-chia.yaml
> Chia 1.7.1

- .github/workflows/main-chia.yaml
- .github/workflows/test-chia.yaml
> Chia 1.7.1 branch

- web/translations/pt_PT/LC_MESSAGES/messages.po
> Update PT translation.

- scripts/pull_3rd_party_libs.sh
> Fix for BSI packaging path change.

- scripts/bladebit_setup.sh
- scripts/forks/chia_install.sh
> Chia 2.1.0 beta

- scripts/plotman_setup.sh
> Fix for broken Plotman dependencies.

- scripts/pull_3rd_party_libs.sh
- web/templates/base.html
- web/templates/charts/container_memory.html
- web/templates/charts/farmed.html
- web/templates/charts/netspace.html
- web/templates/transactions.html
> Merge fix for broken Datatables.js import

- CHANGELOG.md
- common/config/blockchains.json
- scripts/forks/chia_install.sh
- web/static/landings/en.txt
> Chia 2.2.0

- common/config/globals.py
- scripts/forks/chia_launch.sh
- scripts/forks/gigahorse_launch.sh
- web/templates/setup.html
> Account for another year of Chia blockchain DB bloat.

- .github/workflows/develop-chia.yaml
- .github/workflows/main-chia.yaml
- .github/workflows/main-mmx.yaml
- .github/workflows/test-chia.yaml
- .github/workflows/test-mmx.yaml
- CHANGELOG.md
- scripts/forks/chia_install.sh
> More updates

- CHANGELOG.md
- scripts/forks/gigahorse_install.sh
> xz for aarch64 apparently

- scripts/forks/gigahorse_install.sh
> Tar with xz broken in runner?

- scripts/forks/chia_install.sh
> Chia 2.4.3 rc3

- CHANGELOG.md
- scripts/forks/gigahorse_install.sh
> Deal with Gigahorse missing ARM64 support in latest release.

- .github/workflows/develop-chia.yaml
- .github/workflows/main-chia.yaml
- .github/workflows/main-mmx.yaml
- .github/workflows/test-chia.yaml
- .github/workflows/test-mmx.yaml
- CHANGELOG.md
- scripts/forks/gigahorse_install.sh
> Gigahorse at 2.5.0.giga36

- web/models/chia.py
> Fix for regexp handling warning.

- .github/workflows/develop-base.yaml
- .github/workflows/main-base.yaml
- .github/workflows/main-blockchains.yaml
- .github/workflows/test-base.yaml
- .github/workflows/test-blockchains.yaml
> dealing with arm64 breakage

- .github/workflows/develop-base.yaml
- .github/workflows/main-base.yaml
- .github/workflows/main-blockchains.yaml
- .github/workflows/test-base.yaml
- .github/workflows/test-blockchains.yaml
- web/models/chia.py
> Fix issues with arm64

- web/actions/plotman.py
- web/models/chia.py
> More warnings.
